import { checkExportLimit, generateExportFilename, ExportMetadata } from "./export-utils";

export async function exportToExcel(
  data: Record<string, unknown>[],
  columns: { key: string; header: string }[],
  metadata: ExportMetadata
) {
  if (!checkExportLimit(data.length, "xlsx")) return;

  // Lazy load xlsx
  const XLSX = await import("xlsx");

  const mappedData = data.map((row) => {
    const newRow: Record<string, unknown> = {};
    columns.forEach((col) => {
      newRow[col.header] = row[col.key];
    });
    return newRow;
  });

  const wb = XLSX.utils.book_new();

  // 1. Data Sheet
  const wsData = XLSX.utils.json_to_sheet(mappedData);
  XLSX.utils.book_append_sheet(wb, wsData, "Data");

  // 2. Metadata Sheet ("Report Info")
  const reportInfo = [
    { Property: "Generated By", Value: metadata.performedByName || "Unknown" },
    { Property: "Generated At", Value: new Date().toLocaleString() },
    { Property: "Export Format", Value: "Excel (.xlsx)" },
    { Property: "Total Records", Value: metadata.recordCount },
    { Property: "Applied Filters", Value: JSON.stringify(metadata.appliedFilters) },
    { Property: "Correlation ID", Value: metadata.correlationId },
    { Property: "System Version", Value: "0.1.0" },
  ];
  const wsMeta = XLSX.utils.json_to_sheet(reportInfo);
  
  // Set col widths for meta
  wsMeta["!cols"] = [{ wch: 20 }, { wch: 50 }];

  XLSX.utils.book_append_sheet(wb, wsMeta, "Report Info");

  // Save
  XLSX.writeFile(wb, generateExportFilename(metadata.module, "xlsx"));
}
