import { checkExportLimit, generateExportFilename, ExportMetadata } from "./export-utils";

export async function exportToPdf(
  data: Record<string, unknown>[],
  columns: { key: string; header: string }[],
  metadata: ExportMetadata
) {
  if (!checkExportLimit(data.length, "pdf")) return;

  // Lazy load jspdf and jspdf-autotable
  const { jsPDF } = await import("jspdf");
  const autoTableModule = await import("jspdf-autotable");
  const autoTable = autoTableModule.default;

  const doc = new jsPDF("l", "pt", "a4");

  // Title
  const title = `Export - ${metadata.module.toUpperCase()}`;
  doc.setFontSize(16);
  doc.text(title, 40, 40);
  
  // Meta
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated By: ${metadata.performedByName}`, 40, 60);
  doc.text(`Generated At: ${new Date().toLocaleString()}`, 40, 75);
  doc.text(`Total Records: ${metadata.recordCount}`, 40, 90);

  // Table
  const tableData = data.map((row) => columns.map(c => String(row[c.key] ?? "")));
  const tableHeaders = columns.map(c => c.header);

  autoTable(doc, {
    startY: 110,
    head: [tableHeaders],
    body: tableData,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [79, 70, 229] }, // Indigo-600
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  doc.save(generateExportFilename(metadata.module, "pdf"));
}
